apiVersion: checks.dev/v1beta1
kind: PlaywrightCheck
metadata:
  name: example-playwright-check
  labels:
    environment: production
spec:
  language: javascript
  script: |
    const { chromium } = require('playwright');

    (async () => {
    const browser = await chromium.launch();
    const page = await browser.newPage();
    await page.goto('https://example.com');

    // Perform checks
    const title = await page.title();
    if (title !== 'Example Domain') {
        throw new Error(`Title does not match: ${title}`);
    }

    // Check if a specific element is present
    const element = await page.$('text=Example Domain');
    if (!element) {
        throw new Error('Element not found: Example Domain');
    }

    await browser.close();
    })();
  timeout: 120s
  interval: 15m
  retries: 2
  checks:
    - type: script
      operator: equals
      value: "Title does not match"
    - type: script
      operator: contains
      value: "Element not found"
  locations:
    - us-east-1
    - eu-west-2
  notifications:
    - channel: my-webhook-channel
      severity: Critical
