apiVersion: checks.dev/v1beta1
kind: DnsCheck
metadata:
  name: example-dns-check
  labels:
    environment: production
spec:
  hostname: example.com
  recordType: MX
  resolver:
    - 8.8.8.8
  interval: 10m
  retries: 2
  checks:
    - type: recordExists
      operator: equals
      value: true
    - type: recordValue
      operator: equals
      value: "93.184.216.34"
  locations:
    - us-east-1
    - eu-west-2
  channels:
    - channel: my-webhook-channel
      severity: Critical
