apiVersion: checks.dev/v1beta1
kind: HttpCheck
metadata:
  name: example-http-check
  labels:
    environment: production
spec:
  url: https://api.example.com/health
  method: GET
  headers:
    Authorization: Bearer your_access_token_here
  timeout: 5s
  interval: 1m
  retries: 3
  checks:
    - type: statusCode
      operator: equals
      value: 200
    - type: body
      operator: contains
      value: "OK"
    - type: duration
      operator: lessThan
      value: 500ms
    - type: header
      operator: equals
      value: "Content-Type: application/json"

  locations:
    - us-east-1
    - eu-west-2

  channels:
    - channel: my-webhook-channel
      severity: Critical
