apiVersion: checks.dev/v1beta1
kind: SslCheck
metadata:
  name: example-ssl-check
  labels:
    environment: production
spec:
  hostname: example.com
  timeout: 10s
  interval: 1h
  retries: 3
  checks:
    - type: expirationTime
      operator: greaterThan
      value: 30d
    - type: certificateIssuer
      operator: equals
      value: "Let's Encrypt"
    - type: certificateSubject
      operator: contains
      value: "CN=example.com"
  locations:
    - us-east-1
    - eu-west-2
  channels:
    - channel: my-webhook-channel
      severity: Critical
