apiVersion: checks.dev/v1beta1
kind: TcpCheck
metadata:
  name: example-tcp-check
  labels:
    environment: production
spec:
  host: example.com
  port: 80
  timeout: 10s
  interval: 5m
  retries: 2
  checks:
    - type: latency
      operator: lessThan
      value: 200ms
    - type: reachable
      operator: equals
      value: true
  locations:
    - us-east-1
    - eu-west-2
  channels:
    - channel: my-webhook-channel
      severity: Critical
